### PR TITLE
Fix for rectangular images

### PR DESCRIPTION
**Pull request by Azorlogh**

### CODE REVIEW

**Review by jywarren — COMMENTED** [review]
Hmm, thanks, but you're now reverting back to a single F value? Just checking that's not a merge error or something. 

I'll try this code out tomorrow! Any other clues on why this would work better? 

Thank you!

**Comment by SpaVec** [comment]
I found my other shader I wrote doesn't work very well on other photos. I fixed the original fragment.glfs by using the height/width ratio to scale the correction. Actually, the option to change the corrections for x and y isn't really needed now, But it could still be changed by changing lens.ratio

**Comment by jywarren** [comment]
Thanks. Do you think you could share some images it worked better on?

**Comment by jywarren** [comment]
OK, here's a set I had trouble on with the `Fx`, `Fy` version, so for comparison:

Before:

imag0202

With the current (`Fx`, `Fy`) version, i used `a: 1.048, b: 1.059, Fx: 0.09, Fy: 0.22, scale: 1.087, x: 1, y: 1`:

mobius-corrected

And with this PR's combined version, `a: 1.131, b: 1.02, F: 2.11, scale: 0.948, x: 0.981, y: 1`:

combined-f-correct

So, not hugely different?

**Comment by SpaVec** [comment]
This is the result I got :
901991972e4dfd82e0a023c78dcbd735

**Comment by jywarren** [comment]
Are there other images where the difference is greater? This particular test image doesn't look significantly different between the two modes, but I also admit i'm just eyeballing it...

**Comment by SpaVec** [comment]
Here are other examples
saru98o
f659fe26577b7b7c627eb8a2996c61a4
22cb77f9bcc786bc71c9807b3cec3e80

maxresdefault
22db1577827c581eec1db22b7fe1b8d6
474a574b4a6f5158a2f69e1ab2c3e74a

**Comment by jywarren** [comment]
Hi! It's pretty tough to assess these; maybe we have to run some tests on images of various grids or checkerboards. Can you push your branch to your `gh-pages` branch and share a link (as we've done on our demo) so we can run a set of images through it? 

Also just to be clear, we feel you've gone above and beyond on this and really appreciate your input - so no obligation at all! But if you're interested, I can try to ask folks to run some test images through to assess the two approaches and see what works empirically. Thank you!!

**Comment by SpaVec** [comment]
No problem. There you go ! https://spavec.github.io/fisheyegl/example/

**Pull request closed without merging**
